Error executing Python script:

NameError: name 'a' is not defined

Traceback (most recent call last):
  File "data_function.py", line 324, in _execute_script
    exec(compiled_script, self.globals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<data_function>", line 3, in <module>

Standard output:
You should see this!
And this!
