Error executing Python script:

Exception: bepa

Traceback (most recent call last):
  File "data_function.py", line 324, in _execute_script
    exec(compiled_script, self.globals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<data_function>", line 2, in <module>

Standard output:
apa
